[package]
name = "LearnRust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
clap= "4.5.7"

#Libra
assert_approx_eq = "1.1.0"
assert_matches = "1.5.0"

[dev-dependencies]
dotenv = "0.15.0"
